baseURL = "http://flukastudio.me/hugo-portfolio/en/"
languageCode = 'en-us'
title = '>_ Fluka - Portfolio & Blog'
theme = 'hugo-noir' # This is the theme you are usin
# This is the theme you are using

relativeURLs = true
canonifyURLs = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true # Creates URLs like /en/blog/

[languages]
  [languages.en]
    languageName = "English"
    title = "Fluka - Portfolio & Blog"
    weight = 1
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        pageRef = "/about" # Corresponds to content/en/about.md or content/en/about/_index.md
        weight = 1
      [[languages.en.menu.main]]
        name = "Experience"
        pageRef = "/experience"
        weight = 2
      [[languages.en.menu.main]]
        name = "Projects"
        pageRef = "/projects"
        weight = 3
      [[languages.en.menu.main]]
        name = "Blog"
        pageRef = "/blogs" # Assumes a section named 'blogs'
        weight = 4
      [[languages.en.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 5


[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  name = ">_ Fluka"
  profile_image = "/images/profile_placeholder.jpg" # Place in your site's static/images/ directory
  email = "m.benabdelkader02@gmail.com"
  github = "https://github.com/mehdibenabdelkader"
  github_username = "mehdibenabdelkader"
  linkedin = "https://linkedin.com/in/mehdibenabdelkader"
  linkedin_username = "Mehdibenabdelkader"
  twitter = "https://twitter.com/B_MehdiFluka"
  twitter_username = "Mehdi 'Fluka' Benabdelkader"
  discord = "_fluka"

[menu]
  [[menu.main]]
    name = "About"
    pageRef = "/about"
    weight = 1
  [[menu.main]]
    name = "Experience"
    pageRef = "/experience"
    weight = 2
  [[menu.main]]
    name = "Projects"
    pageRef = "/projects"
    weight = 3
  [[menu.main]]
    name = "Blog"
    pageRef = "/blogs"
    weight = 4
  [[menu.main]]
    name = "Contact Me" # Note: "Contact" is used in language-specific menus above for consistency
    pageRef = "/contact"
    weight = 5 